version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "face-sentiment"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pcatkpeq1n2w"
s3_prefix = "face-sentiment"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["FaceSentimentFunction=681261969843.dkr.ecr.us-east-1.amazonaws.com/facesentiment02552640/facesentimentfunctionb509da23repo"]
disable_rollback = true
